### ISSUE TITLE
Broken pypi build

### ISSUE THREAD

**Issue by BonusPlay** [danielplohmann/smda#12]
Sadly package on pypi does not include dependencies, which means performing
```
python -m venv .venv
source .venv/bin/activate
pip install smda
python3 -c "from smda.Disassembler import Disassembler"
```
will fail, as `capstone` dependency is missing.

**Comment by danielplohmann** [comment]
Hi @BonusPlay, thanks for pointing this out! 

TIL: I need to put stuff in "install_requires" in setup.py and not just requirements.txt - it is now fixed in v1.3.1. ;)
