### ISSUE TITLE
Logging is broken

### ISSUE THREAD

**Issue by BonusPlay** [danielplohmann/smda#13]
Currently all files are using
```python
LOGGER = logging.getLogger(__name__)
```
which creates a new logger for each of the files. Moreover, config:
https://github.com/danielplohmann/smda/blob/97a5a6da4d8d83de2a9835ec7d9d247d0a32cee6/smda/SmdaConfig.py#L36-L38
 - doesn't actually assign `self.LOG_LEVEL` to variable passed
 - uses `logging.basicConfig` which overwrites root logger config (that means, any application using smda)

The solution I propse is to replace
```python
logging.getLogger(__name__)
```
with
```python
logging.getLogger("smda")
```
which would make smda use only 1 logger in all of the files and remove call to `logging.basicConfig` in SmdaConfig.

**Comment by danielplohmann** [comment]
Hi,

thanks for the notice!
Using `__name__` for logger instances is imho best practice for multi-module logging, as outlined in the [Python documentation](https://docs.python.org/3/howto/logging.html?highlight=logging#advanced-logging-tutorial). At least I'm not aware that it is harmful to have several dedicated instances.

Overwriting the logging basicConfig is indeed unintended and was introduced when refactoring SMDA increasingly towards being a library. The check for the handler list should normally avoid that it's overwritten when loggers are already present. 
I'll pull that part out of the `SmdaConfig` and put it in the example usage `analyze.py` instead, so there should be no more issues.

**Comment by danielplohmann** [comment]
adressed in v1.3.7 / commit 2c9bf2b1e70cfbe6073c960ee33a429c2a6834cb
