### ISSUE TITLE
SMDA does not recognize imported APIs from ELF files

### ISSUE THREAD

**Issue by williballenthin** [danielplohmann/smda#22]
As triaged in https://github.com/fireeye/capa/issues/725, SMDA doesn't parse imports from ELF files into a representation used for APIs.

I'd propose implementing an `ElfApiResolver` that uses LIEF to parse the ELF imports and responds to `getApi`.

**Comment by williballenthin** [comment]
```py
for relocation in lief.ELF.Binary.relocations:
    if not relocation.has_symbol:
        continue
    if not relocation.symbol.imported:
        continue
    if not relocation.symbol.is_function:
        continue

    # we can't really say what library the symbol came from
    # however, we can treat the version (if present) as relevant metadata?
    lib = None
    if relocation.symbol.has_version and relocation.symbol.symbol_version.has_auxiliary_version:
        # like "GLIBC_2.2.5"
        lib = relocation.symbol.symbol_version.symbol_version_auxiliary.name

    name = relocation.symbol.demangled_name

    print(lib, name)
```

**Comment by williballenthin** [comment]
i'm working on a PR for this. hope to have it to you tomorrow.

**Comment by williballenthin** [comment]
how important is the check `not self.disassembly.isAddrWithinMemoryImage(dereferenced)` here:
https://github.com/danielplohmann/smda/blob/bb9cdab2279f255f5516750160c3a1ff424f8882/smda/intel/IntelDisassembler.py#L179

In the ELF binary I'm using for testing (7351f8a40c5450557b24622417fc478d), the "API thunks" look like `jmp qword ptr [...]` where the to_addr is in the `.got.plt` section and the dereferenced value is a valid address in the `.extern` section. Therefore, `isAddrWithinMemoryImage(dereferenced) == True` and the condition fails, leading to APIs not getting recognized.

I wonder if we can remove this restriction? Alternatively, add another condition to check for "is within the import section?" or similar.

I've been trying to imagine why it was included in the first place. My best guess is that SMDA supports analysis of memory images, and this check is useful with PE files whose import table contains fixed-up pointers to other DLLs in the memory image. Is there a different way we could structure this check to support ELF files, too?

**Comment by williballenthin** [comment]
how important is the check `not self.disassembly.isAddrWithinMemoryImage(dereferenced)` here:
https://github.com/danielplohmann/smda/blob/bb9cdab2279f255f5516750160c3a1ff424f8882/smda/intel/IntelDisassembler.py#L179

In the ELF binary I'm using for testing (7351f8a40c5450557b24622417fc478d), the "API thunks" look like `jmp qword ptr [...]` where the to_addr is in the `.got.plt` section and the dereferenced value is a valid address in the `.extern` section. Therefore, `isAddrWithinMemoryImage(dereferenced) == True` and the condition fails, leading to APIs not getting recognized.

I wonder if we can remove this restriction? Alternatively, add another condition to check for "is within the import section?" or similar.

I've been trying to imagine why it was included in the first place. My best guess is that SMDA supports analysis of memory images, and this check is useful with PE files whose import table contains fixed-up pointers to other DLLs in the memory image. Is there a different way we could structure this check to support ELF files, too?

**Comment by danielplohmann** [comment]
> how important is the check `not self.disassembly.isAddrWithinMemoryImage(dereferenced)` here:
> https://github.com/danielplohmann/smda/blob/bb9cdab2279f255f5516750160c3a1ff424f8882/smda/intel/IntelDisassembler.py#L179
> 
I guess It's not terribly important, not at that point in the code.
I think I primarily included it while analyzing some special cases found in malware.
I observed in more than one family that WinAPIs were not directly used as exported by the respective DLLs but a few instructions "deeper" in, as for example in the custom IAT created by Andromeda where they copy the first instruction before jumping in, or general hook avoidance where WinAPI addr + 5 is used instead.
I also encountered where a DLL was basically force-loaded twice into memory, which screwed with ApiScout expecting the WinAPI addresses in well-known places.
The check for `isAddrWithinMemoryImage()` then also reduces noise by filtering out any `call dword ptr []` targets in the own image as found frequently in some cases, e.g. in Citadel if memory serves correctly.

> In the ELF binary I'm using for testing (7351f8a40c5450557b24622417fc478d), the "API thunks" look like `jmp qword ptr [...]` where the to_addr is in the `.got.plt` section and the dereferenced value is a valid address in the `.extern` section. Therefore, `isAddrWithinMemoryImage(dereferenced) == True` and the condition fails, leading to APIs not getting recognized.
> 
> I wonder if we can remove this restriction? Alternatively, add another condition to check for "is within the import section?" or similar.
> 
I think we can skip the check, or I'll likely move it to the `logging.debug` in the else path.

> I've been trying to imagine why it was included in the first place. My best guess is that SMDA supports analysis of memory images, and this check is useful with PE files whose import table contains fixed-up pointers to other DLLs in the memory image. Is there a different way we could structure this check to support ELF files, too?

Yes, the fix-ups are another case that is comparable to the double-loaded DLLs. :)
I think it's fine how it is solved by you now, checking against the resolvable symbols should be sufficient for what the method wants to achieve.
