### ISSUE TITLE
Are entrypoint(s) and calls_from exposed?

### ISSUE THREAD

**Issue by mr-tz** [danielplohmann/smda#28]
Are the below features exposed and if so, how can I access them?
I'd like to update the SMDA capa backend with this data.

1. entry points, e.g. AddressOfEntryPoint and exported functions
2. optionally calls/xrefs from a function (on a higher level, otherwise I can reuse some existing code)

Thanks!

**Comment by danielplohmann** [comment]
Hey! 
Thanks for pointing this out, this would make a great addition.

I think most of those data points are processed internally already but not nicely exposed right now. 
I'll add some code to make them conveniently available and will provide examples when I close the issue.

**Comment by mr-tz** [comment]
Wow, awesome. Thanks for the quick update!
