### ISSUE TITLE
install fails for Python 3.10

### ISSUE THREAD

**Issue by mike-hunhoff** [danielplohmann/smda#29]
Bumping the `lief` dependency to the latest version (`0.11.5`) fixes the installation failure.

https://github.com/danielplohmann/smda/blob/64ca1705dbe9990a96fd70660fd7a8936e71d707/setup.py#L13

**Comment by danielplohmann** [comment]
Thank you very much for the pointer!
With SMDA v1.7.1 (commit 16599ec), I have changed the Python3 version pin in `setup.py` to LIEF >= 0.11, which should fix the issue. If we run into issues with the "freed" version again, let me know and I'll pin it down to a specific LIEF version again.

**Comment by mike-hunhoff** [comment]
thank you @danielplohmann !
