### ISSUE TITLE
IntelInstructionEscaper  escapeBinary check logic bug

### ISSUE THREAD

**Issue by 1337-42** [danielplohmann/smda#35]
In the `IntelInstructionEscaper` on line 272 there is a flaw in the logic.

```python
if lower_addr is not None and upper_addr is not None and ins.operands.startswith("0x") or ", 0x" in ins.operands:
```
This will sometimes crash if `ins.operands.startswith("0x") or ", 0x" in ins.operands` is `true`.

I think the intended logic here should be:

```python
if lower_addr is not None and upper_addr is not None and (ins.operands.startswith("0x") or ", 0x" in ins.operands):
```

**Comment by danielplohmann** [comment]
You are absolutely correct, seems I ignored binding strength of the logical operators in that if clause. 
Will fix asap - thank you very much!!
