### ISSUE TITLE
Crash when handling InRefs in SMDAReport

### ISSUE THREAD

**Issue by 1337-42** [danielplohmann/smda#36]
In a edge case the disassembler can run into a situation where an incoming Xref is not coming from an instruction offset. This will cause a crash at: https://github.com/danielplohmann/smda/blob/b300eef00ce7924c73c0a36b79a872eb194e38f0/smda/common/SmdaReport.py#L160

The attached file is a example of this. (it is malware, password is infected)
[check.zip](https://github.com/danielplohmann/smda/files/10039915/check.zip)

I added a quick check that will work for our usecase but I'm not sure if it will break anything.

```python
for inref in function.inrefs:
    if inref in offset2ins:
        function.code_inrefs.append(CodeXref(offset2ins[inref], offset2ins[function.offset]))
```

**Comment by danielplohmann** [comment]
thank you very much for reporting this and the proposed fix!
I have confirmed it using the provided data and included the fix in the just published version 1.9.16.
