### ISSUE TITLE
escaping instructions replaces menmonic bytes

### ISSUE THREAD

**Issue by fishfacegit** [danielplohmann/smda#46]
In this case only the [ptr] is replaced.
`IntelInstructionEscaper.escapeBinaryPtrRef: 2 occurrences for ac974a00 in c705ac974a00ac974a00 (mov dword ptr [0x4a97ac], 0x4a97ac), escaping only the first one`

Here might be a problem:
`IntelInstructionEscaper.escapeBinaryPtrRef: 2 occurrences for 05050505 in 010505050505 (add dword ptr [0x5050505], eax), escaping only the first one`

`IntelInstructionEscaper.escapeBinaryPtrRef: 2 occurrences for 05050505 in 020505050505 (add al, byte ptr [0x5050505]), escaping only the first one`

`IntelInstructionEscaper.escapeBinaryPtrRef: 2 occurrences for 05050505 in 030505050505 (add eax, dword ptr [0x5050505]), escaping only the first one`

`IntelInstructionEscaper.escapeBinaryPtrRef: 2 occurrences for 15151515 in 011515151515 (add dword ptr [0x15151515], edx), escaping only the first one`

`IntelInstructionEscaper.escapeBinaryPtrRef: 2 occurrences for 15151515 in 0f101515151515 (movups xmm2, xmmword ptr [0x15151515]), escaping only the first one`

**Comment by danielplohmann** [comment]
Hey! 

Thanks for pointing this out!
Yes, indeed, the way I was locating the offsets so far os agnostic to the structure of the instruction and may harm the mnemonic part. I assumed that it would happen in such rare cases that it would be tolerable. 
This is also related to #37, which also documents inconsistencies and will be addressed very soon.

**Comment by danielplohmann** [comment]
This should be addressed now, see https://github.com/danielplohmann/smda/blob/6d460fe4eaef48ccb79030c9993646e891695b08/tests/testEscaper.py#L32 for all covered test cases and the respective resulting wildcarding.
